<form action="index.php" method="post">

<label for="Name">firstName</label>
<input type="text" id="name" name="firstName">

<label for="lname">lastName</label>
<input type="text" id="lname" name="lastName">

<label for="mail">email</label>
<input type="email" id="mail" name="email">

<label for="pass">password</label>
<input type="password" id="pass" name="password">

<label for="confpass">confirmPassword</label>
<input type="password" id="confpass" name="confirmPassword">

<label for="forname">formName</label>
<input type="text" id="name" name="formName">