<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>RES03 Intégration J11 Exercices Animation</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <?php require './partials/_header.phtml' ?>
        
        <?php if($template === "homepage") {
                require './homepage/homepage.phtml';
            }
            else if($template === "login") {
                require './login/login.phtml';
            }
            else if($require === "register") {
                require './register/register.phtml';
            }
            else if($require === "account") {
                require './account/account.phtml';
            }
            ?>
            <?php require './partials/_footer.phtml' ?>
    </body>
</html>
